// <auto-generated />
namespace MVC_OnlineTicariOtomasyon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_deliverer_column_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_deliverer_column_name));
        
        string IMigrationMetadata.Id
        {
            get { return "202401220707479_update_deliverer_column_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
