// <auto-generated />
namespace MVC_OnlineTicariOtomasyon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class cargo_details_and_cargo_tracking_page : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cargo_details_and_cargo_tracking_page));
        
        string IMigrationMetadata.Id
        {
            get { return "202402091221357_cargo_details_and_cargo_tracking_page"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
